### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KayCen0w0** [nopeAnon/Automated-HoloCure-Fishing#1]
I have met the Requirements, but after opening holocure_fishing.py, it just jumped out of cmd and closed it very quickly, then opened holocure and tried to fish automatically, but it didn’t work.
![image](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/142689383/6a24a4d5-781b-45ca-91fb-5a07037fbe11)
And this is what VScode displayed.

**Comment by tsxkasa** [comment]
install all pywin32 (pip install pypiwin32)
and install OpenCV (pip install opencv-python)

**Comment by nopeAnon** [comment]
My bad. I forgot about the requirements.txt. I have added it now, so you can run `pip install -r requirements.txt` to solve all the dependency issues.
