### ISSUE TITLE
pip: command not found or python was not found

### ISSUE THREAD

**Issue by Prophet147** [nopeAnon/Automated-HoloCure-Fishing#11]
When I am installing the code in Git like this:
$ pip install -r requirements.txt

I am getting this error:
bash: pip: command not found

I am probably just stupid or something so if I can have a small pointer, that would be appreciated :)

**Comment by nopeAnon** [comment]
can you run `python -m pip install -r requirements.txt` and see if it works.

**Comment by Prophet147** [comment]
Python was installed like you had mentioned in the tutorial, and I got this response:

Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by nopeAnon** [comment]
Python wasn't add to the path. Open your python installer and make sure to follow the video below

https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/91358729/55b26dc2-db95-4ae6-9e71-ea37b32d0997

make sure to check "Add Python to environment variables"

after that, restart the git terminal, cd to the repo folder and type `pip install -r requirements.txt`

**Comment by Prophet147** [comment]
got it hang tight

**Comment by Prophet147** [comment]
Many thanks! Problem Solved :)
