### ISSUE TITLE
Invalid format? Can't open/read file

### ISSUE THREAD

**Issue by Roteki** [nopeAnon/Automated-HoloCure-Fishing#12]
Thank you for the video tutorial, it worked perfectly until the last part, where after running 

"$ python ./holocure_fishing.py"

I got the following:
![image](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/48630202/f6de6bc4-f68b-42a4-b518-5849d05152a3)

![image](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/48630202/2c793955-9256-4bf0-9440-039809ee53a8)

Even though the file is obviously right there. About the only thing I can see is that the "\\" and "/" are mixed, but the directory works fine, so I don't know why the inner folder is different.

**Comment by nopeAnon** [comment]
Weird, it should have gotten the path correctly. Looking at the screenshot, the folder name is all lowercase. 

Can you rename the folder from
`automated-holocure-fishing`
to
`Automated-Holocure-Fishing`

If that doesn't work, can you try changing line 10 from:
`dir_path = os.path.dirname(os.path.realpath(__file__))`
to
`dir_path = "."`

**Comment by Roteki** [comment]
Renaming the folder didn't do anything, but the change in line 10 worked, thank you very much!
