### ISSUE TITLE
Can't use the script when Holocure is open on another monitor + solution

### ISSUE THREAD

**Issue by Typhion** [nopeAnon/Automated-HoloCure-Fishing#13]
As the title says it isn't possible to use the script with Holocure on a second monitor.
Solution:
Add this bit of code on top
```
from PIL import ImageGrab
from functools import partial
ImageGrab.grab = partial(ImageGrab.grab, all_screens=True)
```

**Comment by nopeAnon** [comment]
I don't have multiple monitors, so I can't really test it out. But I'll add it in since it still works after being added.

Thank you for the suggestion and solution!

**Comment by Typhion** [comment]
after a bit more testing I've noticed that it does slow down checking for multiple monitors. So it is up to you if you want to keep this in your code! Sorry for suggesting it, I didn't realise it would actually cause the script to miss inputs in the later speeds.

**Comment by nopeAnon** [comment]
I see. For now, I have made the feature optional and will ask the user if they want to enable it or not.
