### ISSUE TITLE
KeyError for buttons except enter

### ISSUE THREAD

**Issue by lugia862** [nopeAnon/Automated-HoloCure-Fishing#14]
Hi! I have encountered a strange problem for that the script seems to be unable to Keydown any directional inputs besides enter, where the first try would result in KeyError, and then does not attempt at all afterwards, but only reacting to Fish Escape message / fish again
If the first key to hit was enter, it would register correctly, so it is only for the directional keys

![KeyError](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/4514268/18961480-cc9e-4e93-9349-783675b83f1f)

**Comment by Napo1898** [comment]
Same here i turned off Auto HDR but its not working

**Comment by nopeAnon** [comment]
Sorry about that. I have forgotten about arrow keys. I haved added it now. See #16
