### ISSUE TITLE
Using MSS for better performance.

### ISSUE THREAD

**Issue by ItsukaHiro** [nopeAnon/Automated-HoloCure-Fishing#20]
I found (on Reddit) that pyautogui is too slow, and people use MSS for better performance

**Comment by nopeAnon** [comment]
Interesting. I'll try to make a prototype of it tomorrow and see how it compares.

**Comment by mindforger** [comment]
do you have a link? i cant pick up anything usefull from google with those three letters XD

**Comment by nopeAnon** [comment]
This is an absolute game changer. It has a 100% accuracy when I switched to it. It took my score to new heights.

![HoloCure_fVrV7a6wbK](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/91358729/6ce1632e-6991-4035-9cb7-7534c6436c74)

I have made a new branch for now. https://github.com/nopeAnon/Automated-HoloCure-Fishing/tree/using-mss-cv2
I'll merge it soon.

Thank you for introducing me to mss!
