### ISSUE TITLE
Window handle invalid

### ISSUE THREAD

**Issue by BeeatZz** [nopeAnon/Automated-HoloCure-Fishing#24]
Hey! i know nothing about computers or coding in general, but following the drive video tutorial, i keep getting this error when trying to run the script 
found keybinds
720p mode set
Traceback (most recent call last):
  File "C:\Users\turle\Documents\AUTOFISHING\Automated-HoloCure-Fishing\holocure
_fishing.py", line 113, in <module>
    win = win32ui.CreateWindowFromHandle(hwndMain)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
win32ui.error: The window handle is invalid.

any idea why this could happen?

**Comment by nopeAnon** [comment]
That happens when you launch the script without the holocure window open. I'll change the behavior in a bit.
