### ISSUE TITLE
there is an issue with the code. 

### ISSUE THREAD

**Issue by Resimaa** [nopeAnon/Automated-HoloCure-Fishing#28]
I have two problems.
first one is this "win32ui.error: The window handle is invalid." the code starts good but then shows some stuff then this idk what this means.
and the second one is that the script works like 60% of the time, it says that it did the key but it didn't  do it in game and just misses the key completely then after missing the one it misses almost all of theme after.

**Comment by nopeAnon** [comment]
Please update to the latest version. That error is from the previous code and shouldn't occur in the new one.

**Comment by Resimaa** [comment]
alright thanks
