### ISSUE TITLE
A and D issue

### ISSUE THREAD

**Issue by zackszackz** [nopeAnon/Automated-HoloCure-Fishing#3]
i think the problem was in A and D keys.. it's runnin, but somehow the game didn't respond to the command. i play on windowed 1280x720

**Comment by nopeAnon** [comment]
A and D is used for the left and right notes.
Can you try updating the repo and see if it fixes it? `git pull origin master`

**Comment by nopeAnon** [comment]
I have made it adapt to your key binds in your config file, so it should fix any input issues
