### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by Resimaa** [nopeAnon/Automated-HoloCure-Fishing#30]
when i start downloading everything it says that there is an update to the program.
do i do it or no?

**Comment by Resimaa** [comment]
and a well done job on fixing all of the problems, now everything runs perfectly even when laggy. 👍

**Comment by nopeAnon** [comment]
I'm assuming it's telling you to update pip. In that case, it is better to update it, but it doesn't really matter in this project. As it doesn't affect it whether you update it or not
