### ISSUE TITLE
Occasionally it stops

### ISSUE THREAD

**Issue by AllieOop** [nopeAnon/Automated-HoloCure-Fishing#31]
Every once and a while the program doesn't reenter fishing.

**Comment by rastorguevia** [comment]
> Every once and a while the program doesn't reenter fishing.

I fixed this problem in my fork, waiting for it to be merged here

**Comment by nopeAnon** [comment]
I have also encountered that bug on rare occasions. The fix made by @rastorguevia should fix it and has been merged
