### ISSUE TITLE
OpenCV error

### ISSUE THREAD

**Issue by FaithfuL11** [nopeAnon/Automated-HoloCure-Fishing#35]
Getting an cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor' when running the script, installed all the required files I believe.

**Comment by nopeAnon** [comment]
That happens when it can't find the images in the img folder. Run the script inside the project folder or launch it using the launch_python.bat

**Comment by FaithfuL11** [comment]
How would I do this? I tried to run it using launch_python.bat  but it can't run cause it is a batch file. I am using VSCode and is it correct/ok if I have the github script folder inside of Python311 folder or should it be somewhere else?

**Comment by FaithfuL11** [comment]
nvm I was able to get it to work I am dumb Running the script in project folder got it working had to try a couple times but it finally works. Ty!
