### ISSUE TITLE
pressing enter only

### ISSUE THREAD

**Issue by tektungg** [nopeAnon/Automated-HoloCure-Fishing#37]
i don't know why but my program just pressed enter button only, so it's not working
![image](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/128006927/d4a02587-f285-4789-bc8c-1567aff9136d)

**Comment by Hexus-One** [comment]
See https://github.com/nopeAnon/Automated-HoloCure-Fishing/issues/38#issuecomment-1712834617 - tl;dr code only works on Win10 at the moment unfortunately

**Comment by tektungg** [comment]
> See [#38 (comment)](https://github.com/nopeAnon/Automated-HoloCure-Fishing/issues/38#issuecomment-1712834617) - tl;dr code only works on Win10 at the moment unfortunately

ah, aight thanks for confirming
