### ISSUE TITLE
False detect

### ISSUE THREAD

**Issue by Hduagvoe** [nopeAnon/Automated-HoloCure-Fishing#38]
So i tried a few of your methods and landed on VS Code, but it's just stuck in this state:
![Screenshot (7589)](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/144579527/05a79512-f087-464d-b7be-71c51b997802)
Then i tried to see what's wrong by changing Debug=False to Debug True... And it seemed to be working well, before i saw the Source window that popped out and turns out all it detected was the title screen
![Screenshot (7590)](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/144579527/5af5dbb8-f930-4bb5-bb63-6567c7174b76)
I tried restarting, turning off Nightlight, restored the keybinds to default but nothing seems to be working.... Do you have a solution for this? thanks

**Comment by Hexus-One** [comment]
Unfortunately the code I wrote is written/tested on Win10 only and not Win11 - something about the screencapture on Win11 needs to be done differently to make it work but I haven't had the time to look into it. If you find a solution, feel free to make a pull request with the new code :)

**Comment by Hduagvoe** [comment]
Ah alright, thanks!

**Comment by nopeAnon** [comment]
The bug is caused by the full-screen window optimization. Please disable it in the holocure.exe > compatibility tab > Enable 'Disable fullscreen optimzations'
