### ISSUE TITLE
how do i run this?

### ISSUE THREAD

**Issue by potatoships222** [nopeAnon/Automated-HoloCure-Fishing#4]

**Comment by nopeAnon** [comment]
1. clone the project or download it as zip and extract it
1. open the project folder
1. open a terminal in the project folder (right click on the folder then click "Open in Terminal")![](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/91358729/69fa6775-28ad-4e07-8348-2c0653c82b0f)
1. then in the terminal, type `pip install -r requirements.txt`
1. Then open holocure, go to holo house and go near the pond where you fish
1. Open the holocure_fishing.py file
1. Start fishing
1. You are done

**Comment by Temoxi** [comment]
it doesn't work for me

**Comment by Temoxi** [comment]
it doesn't work for me (the image is in french because my windows is french)
![Capture d’écran (3)](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/142745293/72304052-5f4d-409a-979c-3af2fb8737fe)
