### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by loweluis** [nopeAnon/Automated-HoloCure-Fishing#40]
After installing everything I stand infront of the pond and open holocure_fishing.py and all it does is this, I tried to wait for a bit and nothing happens. 
![image](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/28964712/286f1673-93db-482e-aedc-a240276dfb84)

**Comment by loweluis** [comment]
Theres no errors at all so I don't know what to do

**Comment by Hexus-One** [comment]
As the instructions say, you have to start fishing first for the program to work :)
