### ISSUE TITLE
cv2 and numpy

### ISSUE THREAD

**Issue by DMOlivia** [nopeAnon/Automated-HoloCure-Fishing#44]
![ảnh](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/147417886/5f1ec6b2-167f-4f05-b2b1-592a57da5ddf)
any way to resolve "cv2" and "numpy" problem?

**Comment by TakeoIschiFan** [comment]
This error occurs if your python installation doesn't detect the third party packages required for the script to run. I assume you want to help develop and not just run?

Basically this program uses a virtual python environment that is specific to this script.
You can learn more about what a virtual environments is [on this page](https://code.visualstudio.com/docs/python/environments).

More specifically, you should run the `prepare.bat` script first, then point vscode to the virtual environment in the .venv folder that has been created using the steps found [here](https://code.visualstudio.com/docs/python/environments#_select-and-activate-an-environment)

**Comment by hdkhanh462** [comment]
Same issue
affter run prepare.bat it only install those:
![image](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/101619460/1761c1e2-1110-4541-bf4f-c9d53a760e71)

Edit: manual install fix the issue
![image](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/101619460/32a49d49-c63f-4d0f-b383-b8e796323d7d)

**Comment by nopeAnon** [comment]
The current program isn't compatible with numpy v2. Please install numpy 1.26.4 to fix this.
