### ISSUE TITLE
bash pip command not found 

### ISSUE THREAD

**Issue by c0c0nu77y** [nopeAnon/Automated-HoloCure-Fishing#48]
when i tried to do the pip install it says the command was not found.

![Screenshot 2024-10-08 155611](https://github.com/user-attachments/assets/b91bea37-ac06-403e-9dfc-8239f12b44b9)

**Comment by nopeAnon** [comment]
python isn't added to your path 
Open the file you used to install python (e.i python-3.11.4-amd64.exe) > Click modify > Click Next > Enable 'Add Python to environment variables' > click Install
