### ISSUE TITLE
it says "key alt not supported, not pressing"

### ISSUE THREAD

**Issue by kalmello** [nopeAnon/Automated-HoloCure-Fishing#50]
![{C5D06A6C-5B32-46FE-9C02-59FCE376E8DF}](https://github.com/user-attachments/assets/b6746219-8786-47d1-ba40-55250cf789f4)

other button is pressed other than space

**Comment by nopeAnon** [comment]
I have added support for alt key in the latest commit. Please update your repo (git pull)
