### ISSUE TITLE
hey i'm new to github and coding 

### ISSUE THREAD

**Issue by Erold007** [nopeAnon/Automated-HoloCure-Fishing#7]
can you make tutorial video so someone who doesn't know about python and coding like me can use it ?

**Comment by Temoxi** [comment]
i agree

**Comment by nopeAnon** [comment]
I have made a video tutorial and added it to the read me.

Follow the tutorial: https://drive.google.com/file/d/14Xha8OWFiv26zBD4cYjMsHLD896q8RH4/view?usp=sharing
