### ISSUE TITLE
Does not attempt any inputs other than 'enter'

### ISSUE THREAD

**Issue by Solidarus** [nopeAnon/Automated-HoloCure-Fishing#8]
![Screenshot 2023-08-20 080309](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/142736653/cedc252b-72b3-46a3-b391-975486441545)

Script does not seem to be able to detect any of the prompts in the box other than the "OK" button.

**Comment by tsxkasa** [comment]
its the way its scripted, some need to be fixed. the Enter is binded to Z and should be fixed, you can fix it by yourself tho.

**Comment by oakami** [comment]
I had the same issue, turning off Auto HDR for HoloCure fixed it for me. It messes up the colors too much.

**Comment by Solidarus** [comment]
> I had the same issue, turning off Auto HDR for HoloCure fixed it for me. It messes up the colors too much.

This was indeed the issue for me. Thanks for the tip!
