### ISSUE TITLE
Why does the bot miss arrows or can't do a good hit?

### ISSUE THREAD

**Issue by Temoxi** [nopeAnon/Automated-HoloCure-Fishing#9]
The bot can't do good and miss some arrow what the probleme

**Comment by nopeAnon** [comment]
The script's default tuning is for golden fishing rod and level 7 speed and HoloCure in the background. 

You can change the [hit area](https://github.com/nopeAnon/Automated-HoloCure-Fishing/blob/8590a905ea6c064bae8ac28f6fbef968c12356da/holocure_fishing.py#L130) to
`region = (hit_area.left+20, hit_area.top+24, hit_area.width-16, hit_area.height-30)`
from
`region = (hit_area.left+14, hit_area.top+24, hit_area.width-16, hit_area.height-30)`
as said by [MichaelC03](https://github.com/nopeAnon/Automated-HoloCure-Fishing/issues/6#issuecomment-1685236892)

However, as the searching area is moved more to the right, it has less time to detect fast moving notes and more likely to miss. So you have to experiment which area is the best.

You can see the area by uncommenting this [line](https://github.com/nopeAnon/Automated-HoloCure-Fishing/blob/9e565abec36b77d949500f22f24fd6c841df35f3/holocure_fishing.py#L179)
